# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-okta-backend-pputman"
    dynamodb_table = "terraform-okta-backend-pputman"
    encrypt        = true
    key            = "accounts/okta-users/terraform.tfstate"
    region         = "us-east-2"
  }
}
